# Generated by Django 3.2 on 2021-05-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Categories',
        ),
    ]
