# Generated by Django 3.2 on 2021-05-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
