# Generated by Django 3.2 on 2021-05-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='text',
            new_name='title',
        ),
    ]
