# Generated by Django 3.2 on 2021-05-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210512_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programming',
            new_name='Books',
        ),
        migrations.DeleteModel(
            name='Autobiography',
        ),
        migrations.DeleteModel(
            name='Fiction',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Magazines',
        ),
        migrations.DeleteModel(
            name='NonFiction',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
    ]
