# Generated by Django 3.2 on 2021-05-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210514_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
