# Generated by Django 3.2 on 2021-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_bookrequest_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(max_length=200, null='false'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='full_name',
            field=models.CharField(max_length=200, null='false'),
        ),
    ]
