# Generated by Django 3.2 on 2021-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210514_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(max_length=200, null='true'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='full_name',
            field=models.CharField(max_length=200, null='true'),
        ),
    ]
