# Generated by Django 3.2 on 2021-05-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210514_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='bName',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
