# Generated by Django 3.2 on 2021-05-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210514_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrequest',
            old_name='bName',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='name',
            new_name='full_name',
        ),
    ]
