# Generated by Django 3.2 on 2021-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210514_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
