# Generated by Django 3.2 on 2021-05-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210514_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='full_name',
        ),
    ]
