# Generated by Django 3.2 on 2021-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_bookrequest_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
