# Generated by Django 3.2 on 2021-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20210514_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='book_name',
            field=models.CharField(default='', max_length=200, null='true'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='full_name',
            field=models.CharField(default='', max_length=200, null='true'),
        ),
    ]
