# Generated by Django 3.2.3 on 2021-05-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210514_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
